apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts.webinar-keptn-staging.35.223.156.234.nip.io
  - carts
  http:
  - route:
    - destination:
        host: carts-canary.webinar-keptn-staging.svc.cluster.local
      weight: 100
    - destination:
        host: carts-primary.webinar-keptn-staging.svc.cluster.local
